### PR TITLE
Add decode() to request.body.

### PR DESCRIPTION
**Pull request by wenbinf**

### CODE REVIEW

**Comment by CCoffie** [comment]
:+1:

**Comment by Stovoy** [comment]
@wenbinf is this good to merge?

**Comment by MoshiMoshi0** [comment]
Why close? This fixes #14

**Comment by wenbinf** [comment]
@devcompl ah, I was not aware of this. I'll put this commit into https://github.com/Nextdoor/ndscheduler/pull/16

**Pull request closed without merging**
